In [5]:
import pandas as pd
from glob import glob



file_list=glob(r"C:\Users\mark\Desktop\Lithuania\*\*.csv")
appended_data = []
for i in file_list:
    city=i.split("\\")[-2]
    data = pd.read_csv(i,dtype=str,on_bad_lines='skip',sep=",",index_col=None,encoding="utf-8")
    # store DataFrame in list
    data["city"]=city
    appended_data.append(data)
# see pd.concat documentation for more info
appended_data = pd.concat(appended_data,ignore_index=True)
column=["Hotel Name","Average Rating","Review Date","Stay Date","Trip Type","Language","Room Description","Title"
         ,"Rating","Text","User Name","Nationality","Value","Service","Sleep Quality","Room","Location","Cleanliness","City","front desk","internet access"]
appended_data.set_axis(column, axis='columns', inplace=True)
df2=appended_data.where(appended_data.notnull(),None)
US_label=["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut",
        "Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas",
          "Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota",
        "Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey",
          "New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
        "Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas",
        "Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]
for i, index in enumerate(df2["Nationality"]):
    if index is None:
        continue
    else:
        if len(index) < 5:
            df2.drop(i,inplace=True)
df2.to_csv("Lithuania.csv",sep=",",index=None, encoding="utf-8")

In [6]:
df2.head()

,Hotel Name,Average Rating,Review Date,Stay Date,Trip Type,Language,Room Description,Title,Rating,Text,...,Nationality,Value,Service,Sleep Quality,Room,Location,Cleanliness,City,front desk,internet access
0,Agneta Apartamentai,5.0,2018-02-08,2018-02-28,FAMILY,en,None,Great place to stay,5,"Place was very cosy, very clean, beds were gre...",...,"Riga, Latvia",None,None,None,None,None,None,Druskininkai_Alytus,None,None
1,Agneta Apartamentai,5.0,2017-03-02,2017-02-28,FRIENDS,en,None,"Very cosy place to stay, great location",5,"Apartments are clean, cosy and comfortable to ...",...,None,5.0,4.0,5.0,None,None,None,Druskininkai_Alytus,None,None
2,Agneta Apartamentai,5.0,2016-08-13,2016-07-31,COUPLES,en,None,Great location good appartments,4,Stayed for 2 nights in July 2016 and was impre...,...,None,None,4.0,3.0,5.0,None,None,Druskininkai_Alytus,None,None
3,Agneta Apartamentai,5.0,2012-08-29,2012-08-31,FAMILY,en,None,Cosy and nice stay in the very center of Drusk...,4,We have spent 4 nights in these apartments dur...,...,"Mortsel, Belgium",4.0,4.0,3.0,5.0,4.0,4.0,Druskininkai_Alytus,None,None
4,Amberton Green Spa Druskininkai,5.0,2021-12-30,2021-09-30,COUPLES,en,None,Best hotel in Lithuania,5,I really sorry for late review. Can't upload t...,...,"London, United Kingdom",None,None,None,None,None,None,Druskininkai_Alytus,None,None

In [30]:
import pandas as pd
from glob import glob
import os

def Hometown_Clean(x,y):
    US_label=["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut",
        "Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas",
          "Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota",
        "Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey",
          "New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
        "Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas",
        "Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]
    Taiwan_label=["Taipei","Hsinchu"]
    for i in x:
        if pd.isna(i) == False:
            mid=i.split(",")[-1]
            if mid.lstrip() in US_label:
                y.replace(i, "United States", inplace=True)
            elif mid.lstrip() == "Falkland Islands":
                y.replace(i, "United Kingdom", inplace=True)
            elif mid.lstrip() == "Centre de Flacq":
                y.replace(i, "Mauritius", inplace=True)
            else:
                y.replace(i, mid.lstrip(), inplace=True)
    for i, index in enumerate(x):
        if index is None:
            continue
        else:
            if len(index) < 3:
                y.drop(i,inplace=True)

#C:\Users\mark\Desktop\Lithuania                
path=input()
file_list=glob(path+r"\*\*.csv")
appended_data = []
for i in file_list:
    city=i.split("\\")[-2]
    size = os.path.getsize(i)
    if size > 948:
        data = pd.read_csv(i,dtype=str,on_bad_lines='skip',sep=",",index_col=None,encoding="utf-8")
        data["city"]=city
        appended_data.append(data)
    # store DataFrame in list

# see pd.concat documentation for more info
appended_data = pd.concat(appended_data,ignore_index=True)
column=["Hotel_Name","Average_Rating","Review_Date","Stay_Date","Trip_Type","Language","Room_Description","Reviw_Title"
         ,"Total_Rating","Reivew_Text","Reviewer_Name","Reviewer_Region","Value","Service","Sleep Quality","Room","Location","Cleanliness","Hotel_City","front desk","internet access"]
appended_data.set_axis(column, axis='columns', inplace=True)
df2=appended_data.where(appended_data.notnull(),None)
print("finish")
Hometown_Clean(df2["Reviewer_Region"],df2)
country=path.split("\\")[-1]
df2["Country"]=country
df2.to_csv(country+".csv",sep=",",index=None, encoding="utf-8")

KeyboardInterrupt: Interrupted by user

In [28]:
appended_data.head()

,Hotel_Name,Average_Rating,Review_Date,Stay_Date,Trip_Type,Language,Room_Description,Reviw_Title,Total_Rating,Reivew_Text,...,Reviewer_Region,Value,Service,Sleep Quality,Room,Location,Cleanliness,Hotel_City,front desk,internet access
0,10Z Bunker,3.5,2020-03-07,2019-05-31,NONE,en,NaN,One in a lifetime,4,I freaked out when I saw that I could stay at ...,...,Maryland,4.0,4.0,5.0,NaN,NaN,Brno,NaN,NaN,NaN
1,10Z Bunker,3.5,2019-11-05,2019-11-30,NONE,en,NaN,More authentic than I imagined:),5,"I have to say, that the stay at the 10-Z Bunke...",...,"Bratislava, Slovakia",5.0,5.0,5.0,NaN,NaN,Brno,NaN,NaN,NaN
2,10Z Bunker,3.5,2019-05-08,2019-05-31,COUPLES,en,NaN,The safest sleep,5,Great atraction for sleep in the nuclear shelt...,...,"Prague, Czech Republic",NaN,NaN,NaN,NaN,NaN,Brno,NaN,NaN,NaN
3,10Z Bunker,3.5,2018-11-12,2018-10-31,SOLO,en,NaN,Specific place,4,Interesting experience if you've expected some...,...,NaN,NaN,NaN,NaN,NaN,NaN,Brno,NaN,NaN,NaN
4,10Z Bunker,3.5,2018-10-29,2018-09-30,COUPLES,en,"It&#39;s a bunker, no external windows, single...",Bizarre! no excuse in this day and age!,1,"As a tourist attraction, place of interest, th...",...,"North Yorkshire, United Kingdom",NaN,5.0,2.0,1.0,NaN,Brno,NaN,NaN,NaN

In [18]:
df2.to_csv(country+".csv",sep=",",index=None, encoding="utf-8")

,Hotel_Name,Average_Rating,Review_Date,Stay_Date,Trip_Type,Language,Room_Description,Reviw_Title,Total_Rating,Reivew_Text,...,Value,Service,Sleep Quality,Room,Location,Cleanliness,Hotel_City,front desk,internet access,Country
0,Agneta Apartamentai,5.0,2018-02-08,2018-02-28,FAMILY,en,None,Great place to stay,5,"Place was very cosy, very clean, beds were gre...",...,None,None,None,None,None,None,Druskininkai_Alytus,None,None,Lithuania
1,Agneta Apartamentai,5.0,2017-03-02,2017-02-28,FRIENDS,en,None,"Very cosy place to stay, great location",5,"Apartments are clean, cosy and comfortable to ...",...,5.0,4.0,5.0,None,None,None,Druskininkai_Alytus,None,None,Lithuania
2,Agneta Apartamentai,5.0,2016-08-13,2016-07-31,COUPLES,en,None,Great location good appartments,4,Stayed for 2 nights in July 2016 and was impre...,...,None,4.0,3.0,5.0,None,None,Druskininkai_Alytus,None,None,Lithuania
3,Agneta Apartamentai,5.0,2012-08-29,2012-08-31,FAMILY,en,None,Cosy and nice stay in the very center of Drusk...,4,We have spent 4 nights in these apartments dur...,...,4.0,4.0,3.0,5.0,4.0,4.0,Druskininkai_Alytus,None,None,Lithuania
4,Amberton Green Spa Druskininkai,5.0,2021-12-30,2021-09-30,COUPLES,en,None,Best hotel in Lithuania,5,I really sorry for late review. Can't upload t...,...,None,None,None,None,None,None,Druskininkai_Alytus,None,None,Lithuania